title: Homelessness and living conditions.
description: GitHub is more than a hosting platform; it is a collaborative ecosystem. By connecting technologists, non-profits, and governments, it can serve as a catalyst for systemic change, empowering communities to tackle homelessness and poor living conditions through technology.
theme: jekyll-theme-cayman
